### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by sudo-suhas** [sudo-suhas/xgo#1]
# Open questions

- [Method signature of `E(...)`](#method-signature-of-e)
- [HTTP Status codes](#http-status-codes)

### Method signature of `E(...)`

Current method signature:

```go
func E(opt Option, opts ...Option) error {
    // ...
}
```

Reason for having 2 parameters is to have compile time check for at least 1
`Option` being passed to the constructor. The downside is that it isn't possible
to spread a slice of `Option`s:

```go
opts := []errors.Option{errors.WithOp(op)}
// Conditionally append Option to opts
return errors.E(opts...)
// not enough arguments in call to E
//    have ([]Option...)
//    want (Option, ...Option)
```

There are 2 workarounds possible.

1. Specify the first parameter explicitly and spread the rest:
   ```go
   var opts []errors.Option
   // ...
   return errors.E(WithOp(op), opts...)
   ```
2. Use `errors.Options` which turns `[]errors.Option` into an `errors.Option`:
   ```go
   opts := []errors.Option{errors.WithOp(op)}
   // ...
   return errors.E(errors.Options(opts))
   ```

The alternative is to only have variadic arguments (`func E(opts ...Option)`).
But this would need to check for length and panic if there were no `Option`s
passed in.

**Question: Should the signature for constructor be changed to have only
variadic arguments?**

### HTTP Status Codes

Error kind to HTTP status code mapping:

| Kind         | HTTP Status Code          |
| -------------------- | ---------------------------- |
| `Unknown`   | `500: Internal Server Error` |
| `Canceled`           | `500: Internal Server Error` |
| `InvalidInput`       | `400: Bad Request`     |
| `DeadlineExceeded`   | `408: Request Timeout`    |
| `NotFound`           | `404: Not Found`          |
| `AlreadyExists`     | **?**            |
| `PermissionDenied`   | `403: Forbidden`          |
| `ResourceExhausted`  | `429: Too Many Requests`    |
| `FailedPrecondition` | `412: Precondition Failed`   |
| `Aborted`   | **?**            |
| `Unimplemented`     | `501: Not Implemented`    |
| `Internal`           | `500: Internal Server Error` |
| `Unavailable`  | `503: Service Unavailable`   |
| `Unauthenticated` | `401: Unauthorized`          |
| `IO`         | **?**            |
| `Illegal`   | **?**            |

**Questions:**

- Are there any `Kind` for which the status code needs to be changed?
- What should be the HTTP status code mapped to the following error kinds:
  - `AlreadyExists`
  - `Aborted`
  - `IO`
  - `Illegal`
- For `409: Conflict`, what would be the appropriate `Kind`?

**Comment by blackvirus18** [comment]
`What should be the HTTP status code mapped to the following error kinds`
We can follow the english conventions corresponding to Int values.
Thoughts?

**Comment by sudo-suhas** [comment]
I am not sure what you mean @blackvirus18 . Could you clarify with an example?

**Comment by sonnes** [comment]
When common errors are defined in library, I am worried about one potential pitfall. 

Would this make it easy to return HTTP errors from store/repository layer, thereby introducing HTTP context into this layer?

Though I like the idea of standardising common errors, while allow custom errors, it will also make it easy to do the wrong thing.
Perhaps, can we prefix or separate errors by layer, scope or purpose where they can be used?

**Comment by sudo-suhas** [comment]
The repository layer is only associating the appropriate 'Kind' of error when returning it. Examples:
- `NotFound` when we get `sql.ErrNoRows`.
- `IO` when opening a connection fails.
- `InvalidInput` when there is an attempt to delete a row with an identifier which isn't present.

The HTTP status code is an attribute of the error `Kind` and not something the repo layer would need to be concerned about.

> Though I like the idea of standardising common errors, while allow custom errors, it will also make it easy to do the wrong thing.
> Perhaps, can we prefix or separate errors by layer, scope or purpose where they can be used?

Not entirely sure what you mean, could you clarify with an example?
The idea is to define error classification which is associated at the lowest layer and the layers higher up can react to or override if required. I don't see why the classification has to be layer-specific.

**Comment by sudo-suhas** [comment]
For "Method signature of E(...)", we have decided to retain the current signature `func E(opt Option, opts ...Option) error`. The reasoning was that the limitations are offset by not having to use panic and the compile time safety of ensuring we always specify an option to the constructor.

The "HTTP Status Codes" were cleaned up in 8adc615.

This is the final mapping from error kinds to HTTP status codes:
 
| Kind                 | HTTP Status Code             |
| -------------------- | ---------------------------- |
| `InvalidInput`       | `400: BadRequest`            |
| `Unauthenticated`    | `401: Unauthorized`          |
| `PermissionDenied`   | `403: Forbidden`             |
| `NotFound`           | `404: NotFound`              |
| `Conflict`           | `409: Conflict`              |
| `FailedPrecondition` | `412: Precondition Failed`   |
| `ResourceExhausted`  | `429: Too Many Requests`     |
| `Internal`           | `500: Internal Server Error` |
| `Canceled`           | `500: Internal Server Error` |
| `Unimplemented`      | `501: Not Implemented`       |
| `Unavailable`        | `503: Service Unavailable`   |
| `DeadlineExceeded`   | `503: Service Unavailable`   |
